### ISSUE TITLE
ポケモンGOによる夜間の騒音によるトラブルについてGOによる夜間の騒音によるトラブルについて（訂正版）

### ISSUE THREAD

**Issue by Miyu2129** [gsc-aoyama/pokemongo4agu#96]
## 問題点
ポケモンGOは時間の制約がないため、夜中もたくさんの人々がハントしている現状です。昨日日本でもポケモンGOが解禁され、とても盛り上がりました。現にアメリカでは、人々が熱中するあまり夜中まで街中に騒音が響き渡り、問題となっています。
## 解決策
夜間におけるポケモンGOの騒音によって、被害者は十分な睡眠を確保できなくなってしまいます。ですから、深夜はポケモンの出現率を低くしたりするなどの工夫を凝らして、夜間にポケモンGOをする人々が騒がないようにするという解決策を導きだしました。

**Comment by mapconcierge** [comment]
元の Issue を継続して修正してください。むやみに Issue を増やさないように！！
